
-- CREATE SEQUENCES (Auto-Increment IDs)

CREATE SEQUENCE seq_member_id START WITH 1000;
CREATE SEQUENCE seq_loan_type_id START WITH 10;
CREATE SEQUENCE seq_loan_id START WITH 5000;
CREATE SEQUENCE seq_deposit_id START WITH 2000;
CREATE SEQUENCE seq_repayment_id START WITH 3000;
CREATE SEQUENCE seq_audit_id START WITH 1;